/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.test;

public class exampleJNI {
  public final static native int gcd(int jarg1, int jarg2);
  public final static native void Foo_set(double jarg1);
  public final static native double Foo_get();
}
