/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.test;

public class example {
  public static int gcd(int x, int y) {
    return exampleJNI.gcd(x, y);
  }

  public static void setFoo(double value) {
    exampleJNI.Foo_set(value);
  }

  public static double getFoo() {
    return exampleJNI.Foo_get();
  }

}
