/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.test;

public class Square extends Shape {
  private long swigCPtr;

  public Square(long cPtr, boolean cMemoryOwn) {
    super(_shapeJNI.Square_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Square obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        _shapeJNI.delete_Square(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Square(double w) {
    this(_shapeJNI.new_Square(w), true);
  }

  public double area() {
    return _shapeJNI.Square_area(swigCPtr, this);
  }

  public double perimeter() {
    return _shapeJNI.Square_perimeter(swigCPtr, this);
  }

}
